Repository jai-deep-24/sneakrHead, pull requests merged in 2023-10, with the labels that each got.

#13 SASS added
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#14 New Modification Added in css
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#15 modifications added continued from yesterday
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#16 Modifying user authentication for protected routes.
  app/Controllers/Http/Admin/ProductController.js
  app/Models/Product.js
  start/routes.js
Labels: HACKTOBERFEST-ACCEPTED

#18 Updations in Css file
  public/style.css
Labels: good first issue, HACKTOBERFEST-ACCEPTED

#17 Cart js enhanced
  cart.js
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#20 Updation in CSS file
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#21 Enhancement in js file
  cart.js
  public/js/scripts.js
Labels: HACKTOBERFEST-ACCEPTED

#22 Updation in js
  public/js/scripts.js
Labels: HACKTOBERFEST-ACCEPTED

#23 Changes in script file
  public/js/scripts.js
Labels: HACKTOBERFEST-ACCEPTED

#24 changes in css
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#26 Enhanced CSS
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#27 Changes in css
  public/css/main.css
Labels: HACKTOBERFEST-ACCEPTED

#28 Changes in Page title
  public/css/styles.css
Labels: HACKTOBERFEST-ACCEPTED

#29 main css code modified
  public/css/main.css
Labels: HACKTOBERFEST-ACCEPTED

#31 Css File Optimized
  public/css/main.css
  public/css/styles.css
Labels: good first issue, HACKTOBERFEST-ACCEPTED
